### ISSUE TITLE
github workflows: don't fail on bandit but display warning

### ISSUE THREAD

**Issue by tpokorra** [basxsoftwareassociation/basxconnect#10]
Sometimes Bandit will give an error, but you only want to fix it later, not immediately.
It would be good if we can display a warning, but not fail the whole job.

See this discussion: https://github.com/actions/toolkit/issues/399

Alternatively, we could use Travis CI, but it seems they are just changing something: 
https://travis-ci.org/getting_started "Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information. "

**Comment by saemideluxe** [comment]
Travis-CI might be worth it, I have seen many projects using it, especially for testing something in a wide range of environments. Let's keep prio low, learning another CI will take  some time to setup. Personally I am prefer GitHub Actions slightly because is directly coupled to the repository, but Travis CI might be the better tool for the job.

We could go with the continue-on-error flag for now?

**Comment by saemideluxe** [comment]
Okay, this is done I think
