### ISSUE TITLE
[BUG] Multiline addresses not displayed as expected

### ISSUE THREAD

**Issue by freebeat** [basxsoftwareassociation/basxconnect#198]
- Detected on: UMCH
- Situation: I add more than 1 line in the address field
- Expected: 
  - It is displayed as 2 lines in the person detail screen
  - It is displayed as 2 lines in the export xls
  - It is displayed as 1 line in the overview
- Actual
  - It is displayed as 1 lines in the person detail screen
  - It is displayed as 1 lines in the export xls
  - It is displayed as 1 line in the overview: Ok

**Comment by wipascal** [comment]
I adapted the formatting of the address field, but I guess for the export you want to have the whole address formatted differently not just this one field, right? 
![image](https://user-images.githubusercontent.com/11404846/144044693-c7abf707-ab43-4002-b590-8c3d8b50aa5f.png)

**Comment by wipascal** [comment]
Actually in the export field a 2-line address field is already displayed as two lines. But the rest just gets joined to one line using commas

**Comment by freebeat** [comment]
Works in overview now, but not in xls export yet for me. Tested on https://urbanmosaic.clients2.basx.dev/ as user beat, using firefox on linux and libre-office calc to check result. E.g. your own contact.

**Comment by saemideluxe** [comment]
There was a bug in the excel-export code where html newlines were
removed instead of replaced with plain-text newlines. I fixed this and
updated connect.basx.ch and urbanmosaic.clients2.basx.dev.

(Also there seemed to be a problem with tags not properly displayed i.e.
without commas, should be fixed as well now).

Quoting Beat Schnyder (2021-12-08 00:21:48)

**Comment by saemideluxe** [comment]
Should be fixed now.

**Comment by freebeat** [comment]
Solved, thanks
