### ISSUE TITLE
"Trash bin" for deleted persons

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#24]
possibility to recover deleted persons

**Comment by saemideluxe** [comment]
Okay, I added the necessary backend for this. As described in the meeting we will only allow soft-deletes for now. Therefore we would only need a suggestion on where in the UI to place the "trash-bin" access (button/menu item, etc).

**Comment by frederikbugglin** [comment]
add new filter named "deleted" to column "State":
![max-1584px-16 column_PERSONEN_Übersicht_V2_Data-Table_Multiselect-Filter_state-open](https://user-images.githubusercontent.com/74606126/115366149-56186280-a1c5-11eb-9719-5dcb7b84fbaa.png)

select the records to be restored and choose "Restore" from the data table toolbar: 
![max-1584px-16 column_PERSONEN_Übersicht_V2_Data-Table_Multiselect-Filter_state-closed_Toolbar](https://user-images.githubusercontent.com/74606126/115366169-5ca6da00-a1c5-11eb-8f60-3bbfb94c1998.png)

**Comment by frederikbugglin** [comment]
displaying/filtering only items, that are deleted, does not work. the filter option "active" is automatically added again and all persons are displayed

**Comment by saemideluxe** [comment]
I see. I will change the checkbox so that the user can only see deleted or undeleted entries at one time but not both at the same time. And when looking at deleted entries (trash) then all deleted items will be displayed, basically ignoring active/inactive (but we can change the behaviour as well). Because rrom the backend view the "active" flag is currently not related to the "deleted" flag. So a person can currently have one of for status:

- not deleted and active
- not deleted and inactive
- deleted and active
- deleted and inactive

My understand is that the inactive status is for persons who should still be inside the database, maybe for later use or somebody whose data should still be kept around. And Deleted is for entries who should no longer appear anywhere. The trash just functions as a last-resort in case somebody mis-clicked something or similar. A person will only be removed completely (emptied from the trash) when we do a privacy-law compliance removal, see #39

**Comment by frederikbugglin** [comment]
deleted person still has state "active" (should be _trashed_ or _deleted_) when in trash bin
<img width="1164" alt="Bildschirmfoto 2021-08-16 um 09 24 26" src="https://user-images.githubusercontent.com/74606126/129526496-ed1cb66e-15e4-4e38-8550-ef47b325419b.png">

**Comment by saemideluxe** [comment]
Status can currently only be "active" or "inactive". It is a different field than "deleted". This would mean that we always set "Status" to "inactive" when a person gets deleted and to "active" when we restore the person, correct @frederikbugglin ?

**Comment by frederikbugglin** [comment]
> This would mean that we always set "Status" to "inactive" when a person gets deleted and to "active" when we restore the person, correct @frederikbugglin ?

correct

**Comment by Matumelo** [comment]
Frederik and I looked at it and decided we need to specify a workflow - a person is active... When does one become inactive? I suggest only inactive persons can be deleted (to avoid mistakes) - what about "referential integrity" - if a person has donated money, shows up in log files for reports... the Data Protection Situation changed since I was in IT... Book Keeping might need data for 10 years... Emails sent might put "Deleted User" instead of the address... Or could we "archive" people? Trash sounds final... What if a person literally dies - never active again, no need to email them but they did not request a delete...  legacy or memory similar to Facebook?  Open for discussion...

**Comment by saemideluxe** [comment]
I can give some answers and thoughts to that:
- The active/inactive pattern is mostly to hide or show entries from the interface and general workflows as far as my understanding goes. The "trash" is for "we don't need that data anymore".
- Currently a person is never (and IMHO should never be) completely removed. Because of referential integrity.
- The biggest issue with this is compliance with data protection laws which require the ability to remove all personal data from a system on request by an individual.
- That is where the ticket #39 comes into play, it should take care of a GDPR-compliant deletion.
- My prefered approach to this would be "blanking" or overwriting of fields with sensitive data. That would keep referential integrity but still comply with necessary data removal.
- One little issue is that we keep revision of all person-entries. So we have to go through all revisions and delete entries there as well.
- The biggest issue (but this is outside of our hands) is how to deal with entries which have been backed-up to some place somewhere and could potentially be restored. That depends completely on the exact project and deployment strategy.
- For removal of historical data we would need something like a "scheduled" (GDPR-compliant) deletion.

**Comment by saemideluxe** [comment]
Closing in favor of #39.
Let us continue this in the GDPR ticket since this feature/bug is resolved on itself.
If somebody finds "Archive" a better option open a new ticket. I am not sure if this is a simple renaming or has more implications regarding implemenation *and* semantics.
