### ISSUE TITLE
Settings / General

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#28]
- [x] Remove form field "Typ"
- [x] Change current field names according to design
- [x] max. column width = span? 6 cols
- [ ] Optional: Add logo upload functionality (for branding purposes, e.g. used in ui shell header or for future PDF-Reports, etc.)

![Allgemein](https://user-images.githubusercontent.com/74606126/111321193-fed41f00-8667-11eb-8381-3c357a9a0a97.png)

<img width="1164" alt="Bildschirmfoto 2021-03-16 um 14 56 32" src="https://user-images.githubusercontent.com/74606126/111321123-f1b73000-8667-11eb-83bb-698e72c48dba.png">

**Comment by saemideluxe** [comment]
The grid-defintions in the carbon design CSS only define the flexible grid, not the fixed grid. I assume the 6 columns refer to fixed-sized columns? Since the CSS definitions are not really clear about that (or I do not yet parse it correctly), I will assume one column to be 10 mini units (8px). And therefore setting the max-width to 480px (8px * 10 * 6). It looks correct

**Comment by saemideluxe** [comment]
The "optional" is not done yet, I wonder whether we should add the "logo/profile picture" field to all persons? If not I will just a single one, if yes I suggest we open a new issue in order to track the progress on that.

**Comment by frederikbugglin** [comment]
> The "optional" is not done yet, I wonder whether we should add the "logo/profile picture" field to all persons?

I guess they won't need this.

**Comment by frederikbugglin** [comment]
Add a single upload logo component to Settings/General as shown above. And See issue #36.
