### ISSUE TITLE
Excel-Dowloads: Separate name field into first and last name fields 

### ISSUE THREAD

**Issue by frederikbugglin** [basxsoftwareassociation/basxconnect#87]

**Comment by saemideluxe** [comment]
@frederikbugglin Suggestion: In order to keep the excel export generic (meaing always exporting the same columns that are displayed in the person-browse view) we display first name and last name in the person browse view by default and then generate the excel accordingly.

**Comment by frederikbugglin** [comment]
I totally agree on that.
> we display first name and last name in the person browse view by default and then generate the excel accordingly

**Comment by saemideluxe** [comment]
Okay, after looking at it that turned out to be a problem: If we add fields to the table which are specific to natural person (or any field which is not shared for all 3 person types) then that field cannot be sorted. This means if we add Last Name and First Name to the table, these two columns can not be sorted. The problem is that the database-backend as it is does not allow to filter on fields which are only available on some objects but not on others. So, I went back and added the first name and last name only in the excel export. I will upload it like that if you agree.

P.S.
I think a nice-to-have in the future might be that we extend the database-backend to allow sorting on non-existing fields (like sorting on first_name and treating legal person and person associations just like they have an empty value there). But it would require some thinking on how to implement it properly.

**Comment by frederikbugglin** [comment]
> I will upload it like that if you agree.

Go ahead, I agree :-)

**Comment by saemideluxe** [comment]
This should be working now, on public demo and on the clients testing instance

**Comment by frederikbugglin** [comment]
**Test Environment** DEMO, PWS STAGING
**Test case** Name and Vorname should be separate fields
**Menu name** Personen/
**Action taken** Selected multiple data entries, downloaded excel file from the data table action bar.
**Expected result**  Name and Vorname are separate fields
**Test result(s)** _successful_ or _failed_

#### **Further action steps**
- [ ] @frederikbugglin Test on PWS LIVE after deployment

**Comment by saemideluxe** [comment]
Okay, I deployed to PWS LIVE.
